from typing import Any, Awaitable, Callable, Optional

class Event:
    def cancel(self) -> Awaitable[None]: ...
    player: "Player"
    entity: "Entity"
    block: "Block"
    world: "World"
    location: "Location"
    item: "Item"
    inventory: "Inventory"
    chunk: "Chunk"

class Player(Entity):
    name: str
    uuid: str
    location: "Location"
    world: "World"
    game_mode: "GameMode"
    health: float
    food_level: int
    inventory: "Inventory"
    def send_message(self, message: str) -> Awaitable[None]: ...
    def chat(self, message: str) -> Awaitable[None]: ...
    def kick(self, reason: str = "") -> Awaitable[None]: ...
    def teleport(self, location: "Location") -> Awaitable[None]: ...
    def give_exp(self, amount: int) -> Awaitable[None]: ...
    def add_effect(self, effect: "Effect") -> Awaitable[None]: ...
    def remove_effect(self, effect_type: "EffectType") -> Awaitable[None]: ...
    def effects(self) -> Awaitable[list["Effect"]]: ...
    def set_game_mode(self, mode: "GameMode") -> Awaitable[None]: ...
    def scoreboard(self) -> Awaitable["Scoreboard"]: ...
    def set_scoreboard(self, scoreboard: "Scoreboard") -> Awaitable[None]: ...
    def has_permission(self, permission: str) -> Awaitable[bool]: ...
    def is_op(self) -> Awaitable[bool]: ...
    def set_op(self, value: bool) -> Awaitable[None]: ...
    def play_sound(self, sound: "Sound", volume: float = 1.0, pitch: float = 1.0) -> Awaitable[None]: ...
    def send_action_bar(self, message: str) -> Awaitable[None]: ...
    def send_title(self, title: str, subtitle: str = "", fade_in: int = 10, stay: int = 70, fade_out: int = 20) -> Awaitable[None]: ...
    def set_health(self, health: float) -> Awaitable[None]: ...
    def set_food_level(self, level: int) -> Awaitable[None]: ...
    def level(self) -> Awaitable[int]: ...
    def set_level(self, level: int) -> Awaitable[None]: ...
    def exp(self) -> Awaitable[float]: ...
    def set_exp(self, exp: float) -> Awaitable[None]: ...
    def is_flying(self) -> Awaitable[bool]: ...
    def set_flying(self, value: bool) -> Awaitable[None]: ...
    def is_sneaking(self) -> Awaitable[bool]: ...
    def set_sneaking(self, value: bool) -> Awaitable[None]: ...
    def is_sprinting(self) -> Awaitable[bool]: ...
    def set_sprinting(self, value: bool) -> Awaitable[None]: ...
    def set_walk_speed(self, speed: float) -> Awaitable[None]: ...
    def set_fly_speed(self, speed: float) -> Awaitable[None]: ...

class Entity:
    uuid: str
    type: "EntityType"
    location: "Location"
    world: "World"
    def teleport(self, location: "Location") -> Awaitable[None]: ...
    def remove(self) -> Awaitable[None]: ...
    def set_velocity(self, vector: "Vector") -> Awaitable[None]: ...
    def velocity(self) -> Awaitable["Vector"]: ...
    def is_dead(self) -> Awaitable[bool]: ...
    def is_valid(self) -> Awaitable[bool]: ...
    def fire_ticks(self) -> Awaitable[int]: ...
    def set_fire_ticks(self, ticks: int) -> Awaitable[None]: ...
    def add_passenger(self, entity: "Entity") -> Awaitable[bool]: ...
    def remove_passenger(self, entity: "Entity") -> Awaitable[bool]: ...
    def passengers(self) -> Awaitable[list["Entity"]]: ...
    def custom_name(self) -> Awaitable[Any]: ...
    def set_custom_name(self, name: str) -> Awaitable[None]: ...
    def set_custom_name_visible(self, value: bool) -> Awaitable[None]: ...

class EntityType: ...

class World:
    name: str
    uuid: str
    environment: Any
    def block_at(self, x: int, y: int, z: int) -> Awaitable["Block"]: ...
    def spawn_entity(self, location: "Location", entity_type: "EntityType") -> Awaitable["Entity"]: ...
    def chunk_at(self, x: int, z: int) -> Awaitable["Chunk"]: ...
    def spawn(self, location: "Location", entity_cls: type) -> Awaitable["Entity"]: ...
    def set_time(self, time: int) -> Awaitable[None]: ...
    def time(self) -> Awaitable[int]: ...
    def set_difficulty(self, difficulty: "Difficulty") -> Awaitable[None]: ...
    def difficulty(self) -> Awaitable["Difficulty"]: ...
    def players(self) -> Awaitable[list["Player"]]: ...
    def spawn_particle(self, particle: "Particle", location: "Location", count: int = 1, offset_x: float = 0, offset_y: float = 0, offset_z: float = 0, extra: float = 0) -> Awaitable[None]: ...
    def play_sound(self, location: "Location", sound: "Sound", volume: float = 1.0, pitch: float = 1.0) -> Awaitable[None]: ...
    def strike_lightning(self, location: "Location") -> Awaitable["Entity"]: ...
    def strike_lightning_effect(self, location: "Location") -> Awaitable[None]: ...
    def spawn_location(self) -> Awaitable["Location"]: ...
    def set_spawn_location(self, location: "Location") -> Awaitable[None]: ...
    def full_time(self) -> Awaitable[int]: ...
    def set_full_time(self, time: int) -> Awaitable[None]: ...
    def has_storm(self) -> Awaitable[bool]: ...
    def set_storm(self, value: bool) -> Awaitable[None]: ...
    def is_thundering(self) -> Awaitable[bool]: ...
    def set_thundering(self, value: bool) -> Awaitable[None]: ...
    def weather_duration(self) -> Awaitable[int]: ...
    def set_weather_duration(self, ticks: int) -> Awaitable[None]: ...
    def thunder_duration(self) -> Awaitable[int]: ...
    def set_thunder_duration(self, ticks: int) -> Awaitable[None]: ...

class Dimension: ...

class Location:
    x: float
    y: float
    z: float
    yaw: float
    pitch: float
    world: "World"
    def add(self, x: float, y: float, z: float) -> Awaitable["Location"]: ...
    def clone(self) -> Awaitable["Location"]: ...
    def distance(self, other: "Location") -> Awaitable[float]: ...
    def distance_squared(self, other: "Location") -> Awaitable[float]: ...
    def set_world(self, world: "World") -> Awaitable[None]: ...

class Block:
    x: int
    y: int
    z: int
    type: "Material"
    location: "Location"
    world: "World"
    def break_naturally(self) -> Awaitable[None]: ...
    def set_type(self, material: "Material") -> Awaitable[None]: ...
    def is_solid(self) -> Awaitable[bool]: ...
    def data(self) -> Awaitable[Any]: ...
    def set_data(self, data: Any) -> Awaitable[None]: ...
    def light_level(self) -> Awaitable[int]: ...
    def biome(self) -> Awaitable["Biome"]: ...
    def set_biome(self, biome: "Biome") -> Awaitable[None]: ...

class Chunk:
    x: int
    z: int
    world: "World"
    def load(self) -> Awaitable[bool]: ...
    def unload(self) -> Awaitable[bool]: ...
    def is_loaded(self) -> Awaitable[bool]: ...

class Inventory:
    size: int
    contents: list["Item"]
    holder: Any
    def add_item(self, item: "Item") -> Awaitable[Any]: ...
    def remove_item(self, item: "Item") -> Awaitable[Any]: ...
    def clear(self) -> Awaitable[None]: ...
    def first_empty(self) -> Awaitable[int]: ...
    def get_item(self, slot: int) -> Awaitable["Item"]: ...
    def set_item(self, slot: int, item: "Item") -> Awaitable[None]: ...
    def contains(self, material: "Material", amount: int = 1) -> Awaitable[bool]: ...

class ItemMeta:
    hasCustomModelData: bool
    customModelData: int
    def set_custom_model_data(self, value: int) -> Awaitable[None]: ...
    def has_lore(self) -> Awaitable[bool]: ...
    def lore(self) -> Awaitable[list[str]]: ...
    def set_lore(self, lore: list[str]) -> Awaitable[None]: ...

class Item:
    type: "Material"
    amount: int
    meta: "ItemMeta"
    def set_amount(self, value: int) -> Awaitable[None]: ...
    def set_meta(self, meta: "ItemMeta") -> Awaitable[None]: ...
    def clone(self) -> Awaitable["Item"]: ...
    def is_similar(self, other: "Item") -> Awaitable[bool]: ...
    def max_stack_size(self) -> Awaitable[int]: ...

class Material: ...

class Biome: ...

class Effect:
    type: "EffectType"
    duration: int
    amplifier: int
    ambient: bool
    particles: bool
    icon: bool
    def with_duration(self, duration: int) -> Awaitable["Effect"]: ...
    def with_amplifier(self, amplifier: int) -> Awaitable["Effect"]: ...

class EffectType: ...

class AttributeType: ...

class Attribute:
    def attribute_type(self) -> Awaitable["AttributeType"]: ...
    def value(self) -> Awaitable[float]: ...
    def base_value(self) -> Awaitable[float]: ...
    def set_base_value(self, value: float) -> Awaitable[None]: ...

class GameMode: ...
class Sound: ...
class Particle: ...
class Difficulty: ...

class Vector:
    x: float
    y: float
    z: float

class BarColor: ...
class BarStyle: ...

class BossBar:
    def add_player(self, player: "Player") -> Awaitable[None]: ...
    def remove_player(self, player: "Player") -> Awaitable[None]: ...
    def title(self) -> Awaitable[str]: ...
    def set_title(self, title: str) -> Awaitable[None]: ...
    def progress(self) -> Awaitable[float]: ...
    def set_progress(self, value: float) -> Awaitable[None]: ...
    def color(self) -> Awaitable["BarColor"]: ...
    def set_color(self, color: "BarColor") -> Awaitable[None]: ...
    def style(self) -> Awaitable["BarStyle"]: ...
    def set_style(self, style: "BarStyle") -> Awaitable[None]: ...
    def visible(self) -> Awaitable[bool]: ...
    def set_visible(self, value: bool) -> Awaitable[None]: ...

class Scoreboard:
    def register_objective(self, name: str, criteria: str, display_name: str = "") -> Awaitable["Objective"]: ...
    def get_team(self, name: str) -> Awaitable["Team"]: ...
    def register_team(self, name: str) -> Awaitable["Team"]: ...
    def get_objective(self, name: str) -> Awaitable["Objective"]: ...
    def objectives(self) -> Awaitable[list["Objective"]]: ...
    def teams(self) -> Awaitable[list["Team"]]: ...
    def clear_slot(self, slot: Any) -> Awaitable[None]: ...

class Team:
    def add_entry(self, entry: str) -> Awaitable[None]: ...
    def remove_entry(self, entry: str) -> Awaitable[None]: ...
    def set_prefix(self, prefix: str) -> Awaitable[None]: ...
    def set_suffix(self, suffix: str) -> Awaitable[None]: ...
    def color(self) -> Awaitable[Any]: ...
    def set_color(self, color: Any) -> Awaitable[None]: ...
    def entries(self) -> Awaitable[set[str]]: ...

class Objective:
    def set_display_name(self, name: str) -> Awaitable[None]: ...
    def get_score(self, entry: str) -> Awaitable[Any]: ...
    def name(self) -> Awaitable[str]: ...
    def criteria(self) -> Awaitable[str]: ...
    def display_slot(self) -> Awaitable[Any]: ...
    def set_display_slot(self, slot: Any) -> Awaitable[None]: ...

class Advancement:
    def key(self) -> Awaitable[Any]: ...

class AdvancementProgress:
    def is_done(self) -> Awaitable[bool]: ...
    def award_criteria(self, name: str) -> Awaitable[bool]: ...
    def revoke_criteria(self, name: str) -> Awaitable[bool]: ...
    def remaining_criteria(self) -> Awaitable[set[str]]: ...
    def awarded_criteria(self) -> Awaitable[set[str]]: ...

class Potion:
    def type(self) -> Awaitable[Any]: ...
    def level(self) -> Awaitable[int]: ...

class Server:
    def broadcast(self, message: str) -> Awaitable[None]: ...
    def players(self) -> Awaitable[list["Player"]]: ...
    def worlds(self) -> Awaitable[list["World"]]: ...
    def world(self, name: str) -> Awaitable["World"]: ...
    def scoreboard_manager(self) -> Awaitable[Any]: ...
    def create_boss_bar(self, title: str, color: "BarColor", style: "BarStyle") -> Awaitable["BossBar"]: ...
    def get_boss_bars(self) -> Awaitable[list["BossBar"]]: ...
    def get_advancement(self, key: str) -> Awaitable["Advancement"]: ...
    def plugin_manager(self) -> Awaitable[Any]: ...
    def scheduler(self) -> Awaitable[Any]: ...
    name: str
    version: str
    motd: str
    max_players: int

class Chat:
    def broadcast(self, message: str) -> Awaitable[None]: ...

class Reflect:
    def clazz(self, name: str) -> Awaitable[Any]: ...

server: Server
chat: Chat
reflect: Reflect


def event(func: Optional[Callable] = None, *, once_per_tick: bool = False): ...

def command(name: Optional[str] = None): ...
