from typing import Any, Awaitable, Callable, Optional

class EntityGoneException(Exception): ...

class RaycastResult:
    x: float
    y: float
    z: float
    entity: "Entity" | None
    block: "Block" | None
    start_x: float
    start_y: float
    start_z: float
    yaw: float
    pitch: float

class Event:
    def cancel(self) -> Awaitable[None]: ...
    player: "Player"
    entity: "Entity"
    block: "Block"
    world: "World"
    location: "Location"
    item: "Item"
    inventory: "Inventory"
    chunk: "Chunk"
    slot: int

class Player(Entity):
    def __init__(self, uuid: str | None = None, name: str | None = None): ...
    name: str
    uuid: str
    location: "Location"
    world: "World"
    game_mode: "GameMode"
    health: float
    food_level: int
    inventory: "Inventory"
    def send_message(self, message: str) -> Awaitable[None]: ...
    def chat(self, message: str) -> Awaitable[None]: ...
    def kick(self, reason: str = "") -> Awaitable[None]: ...
    def teleport(self, location: "Location") -> Awaitable[None]: ...
    def give_exp(self, amount: int) -> Awaitable[None]: ...
    def add_effect(self, effect: "Effect") -> Awaitable[None]: ...
    def remove_effect(self, effect_type: "EffectType") -> Awaitable[None]: ...
    effects: list["Effect"]
    def set_game_mode(self, mode: "GameMode") -> Awaitable[None]: ...
    scoreboard: "Scoreboard"
    def set_scoreboard(self, scoreboard: "Scoreboard") -> Awaitable[None]: ...
    def has_permission(self, permission: str) -> Awaitable[bool]: ...
    is_op: bool
    def set_op(self, value: bool) -> Awaitable[None]: ...
    def add_permission(self, permission: str, value: bool = True) -> Awaitable[bool]: ...
    def remove_permission(self, permission: str) -> Awaitable[bool]: ...
    permission_groups: list[str]
    primary_group: str | None
    def has_group(self, group: str) -> Awaitable[bool]: ...
    def add_group(self, group: str) -> Awaitable[bool]: ...
    def remove_group(self, group: str) -> Awaitable[bool]: ...
    def play_sound(self, sound: "Sound", volume: float = 1.0, pitch: float = 1.0) -> Awaitable[None]: ...
    def send_action_bar(self, message: str) -> Awaitable[None]: ...
    def send_title(self, title: str, subtitle: str = "", fade_in: int = 10, stay: int = 70, fade_out: int = 20) -> Awaitable[None]: ...
    def set_health(self, health: float) -> Awaitable[None]: ...
    def set_food_level(self, level: int) -> Awaitable[None]: ...
    level: int
    def set_level(self, level: int) -> Awaitable[None]: ...
    exp: float
    def set_exp(self, exp: float) -> Awaitable[None]: ...
    is_flying: bool
    def set_flying(self, value: bool) -> Awaitable[None]: ...
    is_sneaking: bool
    def set_sneaking(self, value: bool) -> Awaitable[None]: ...
    is_sprinting: bool
    def set_sprinting(self, value: bool) -> Awaitable[None]: ...
    def set_walk_speed(self, speed: float) -> Awaitable[None]: ...
    def set_fly_speed(self, speed: float) -> Awaitable[None]: ...

class Entity:
    def __init__(self, uuid: str | None = None): ...
    @classmethod
    def spawn(cls, entity_type: "EntityType" | str, location: "Location", **kwargs: Any) -> Awaitable["Entity"]: ...
    uuid: str
    type: "EntityType"
    location: "Location"
    world: "World"
    def teleport(self, location: "Location") -> Awaitable[None]: ...
    def remove(self) -> Awaitable[None]: ...
    def set_velocity(self, vector: "Vector") -> Awaitable[None]: ...
    velocity: "Vector"
    is_dead: bool
    is_alive: bool
    is_valid: bool
    fire_ticks: int
    def set_fire_ticks(self, ticks: int) -> Awaitable[None]: ...
    def add_passenger(self, entity: "Entity") -> Awaitable[bool]: ...
    def remove_passenger(self, entity: "Entity") -> Awaitable[bool]: ...
    passengers: list["Entity"]
    custom_name: Any
    def set_custom_name(self, name: str) -> Awaitable[None]: ...
    def set_custom_name_visible(self, value: bool) -> Awaitable[None]: ...

class EntityType: ...

class World:
    def __init__(self, name: str | None = None): ...
    name: str
    uuid: str
    environment: Any
    def block_at(self, x: int, y: int, z: int) -> Awaitable["Block"]: ...
    def spawn_entity(self, location: "Location", entity_type: "EntityType" | str, **kwargs: Any) -> Awaitable["Entity"]: ...
    def chunk_at(self, x: int, z: int) -> Awaitable["Chunk"]: ...
    def spawn(self, location: "Location", entity_cls: type | "EntityType" | str, **kwargs: Any) -> Awaitable["Entity"]: ...
    def set_time(self, time: int) -> Awaitable[None]: ...
    time: int
    def set_difficulty(self, difficulty: "Difficulty") -> Awaitable[None]: ...
    difficulty: "Difficulty"
    players: list["Player"]
    def spawn_particle(self, particle: "Particle", location: "Location", count: int = 1, offset_x: float = 0, offset_y: float = 0, offset_z: float = 0, extra: float = 0) -> Awaitable[None]: ...
    def play_sound(self, location: "Location", sound: "Sound", volume: float = 1.0, pitch: float = 1.0) -> Awaitable[None]: ...
    def strike_lightning(self, location: "Location") -> Awaitable["Entity"]: ...
    def strike_lightning_effect(self, location: "Location") -> Awaitable[None]: ...
    spawn_location: "Location"
    def set_spawn_location(self, location: "Location") -> Awaitable[None]: ...
    full_time: int
    def set_full_time(self, time: int) -> Awaitable[None]: ...
    has_storm: bool
    def set_storm(self, value: bool) -> Awaitable[None]: ...
    is_thundering: bool
    def set_thundering(self, value: bool) -> Awaitable[None]: ...
    weather_duration: int
    def set_weather_duration(self, ticks: int) -> Awaitable[None]: ...
    thunder_duration: int
    def set_thunder_duration(self, ticks: int) -> Awaitable[None]: ...

class Dimension: ...

class Location:
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, world: "World" | str | None = None, yaw: float = 0.0, pitch: float = 0.0): ...

    x: float
    y: float
    z: float
    yaw: float
    pitch: float
    world: "World"
    def add(self, x: float, y: float, z: float) -> Awaitable["Location"]: ...
    def clone(self) -> Awaitable["Location"]: ...
    def distance(self, other: "Location") -> Awaitable[float]: ...
    def distance_squared(self, other: "Location") -> Awaitable[float]: ...
    def set_world(self, world: "World") -> Awaitable[None]: ...

class Block:
    def __init__(self, world: "World" | str | None = None, x: int | None = None, y: int | None = None, z: int | None = None, material: "Material" | str | None = None): ...
    @classmethod
    def create(cls, location: "Location", material: "Material" | str) -> Awaitable["Block"]: ...
    x: int
    y: int
    z: int
    type: "Material"
    location: "Location"
    world: "World"
    def break_naturally(self) -> Awaitable[None]: ...
    def set_type(self, material: "Material") -> Awaitable[None]: ...
    is_solid: bool
    data: Any
    def set_data(self, data: Any) -> Awaitable[None]: ...
    light_level: int
    biome: "Biome"
    def set_biome(self, biome: "Biome") -> Awaitable[None]: ...

class Chunk:
    def __init__(self, world: "World" | str | None = None, x: int | None = None, z: int | None = None): ...
    x: int
    z: int
    world: "World"
    def load(self) -> Awaitable[bool]: ...
    def unload(self) -> Awaitable[bool]: ...
    is_loaded: bool

class Inventory:
    def __init__(self, size: int = 9, title: str = "", contents: list["Item"] | None = None): ...
    size: int
    contents: list["Item"]
    holder: Any
    title: str
    def open(self, player: "Player") -> Awaitable[Any]: ...
    def add_item(self, item: "Item") -> Awaitable[Any]: ...
    def remove_item(self, item: "Item") -> Awaitable[Any]: ...
    def clear(self) -> Awaitable[None]: ...
    def close(self, player: "Player" | None = None) -> Awaitable[Any]: ...
    first_empty: int
    def get_item(self, slot: int) -> Awaitable["Item"]: ...
    def set_item(self, slot: int, item: "Item") -> Awaitable[None]: ...
    def contains(self, material: "Material", amount: int = 1) -> Awaitable[bool]: ...

class Item:
    def __init__(self, material: "Material" | str | None = None, amount: int = 1, name: str | None = None, lore: list[str] | None = None, custom_model_data: int | None = None, attributes: list[dict[str, Any]] | None = None, nbt: dict[str, Any] | None = None): ...
    @classmethod
    def drop(cls, material: "Material" | str, location: "Location", amount: int = 1, **kwargs: Any) -> Awaitable["Entity"]: ...
    @classmethod
    def give(cls, player: "Player", material: "Material" | str, amount: int = 1, **kwargs: Any) -> Awaitable[Any]: ...
    type: "Material"
    amount: int
    name: str | None
    lore: list[str]
    custom_model_data: int | None
    attributes: list[dict[str, Any]]
    nbt: dict[str, Any]
    def set_amount(self, value: int) -> Awaitable[None]: ...
    def set_name(self, name: str) -> Awaitable[None]: ...
    def set_lore(self, lore: list[str]) -> Awaitable[None]: ...
    def set_custom_model_data(self, value: int) -> Awaitable[None]: ...
    def set_attributes(self, attributes: list[dict[str, Any]]) -> Awaitable[None]: ...
    def set_nbt(self, nbt: dict[str, Any]) -> Awaitable[None]: ...
    def clone(self) -> Awaitable["Item"]: ...
    def is_similar(self, other: "Item") -> Awaitable[bool]: ...
    max_stack_size: int

class Material:
    def __init__(self, name: str, _name: str | None = None): ...

class Biome: ...

class Effect:
    @classmethod
    def apply(cls, player: "Player", effect_type: "EffectType" | str | None = None, duration: int = 0, amplifier: int = 0, ambient: bool = False, particles: bool = True, icon: bool = True) -> Awaitable[Any]: ...
    def __init__(self, effect_type: "EffectType" | str | None = None, duration: int = 0, amplifier: int = 0, ambient: bool = False, particles: bool = True, icon: bool = True): ...
    type: "EffectType"
    duration: int
    amplifier: int
    ambient: bool
    particles: bool
    icon: bool
    def with_duration(self, duration: int) -> Awaitable["Effect"]: ...
    def with_amplifier(self, amplifier: int) -> Awaitable["Effect"]: ...

class EffectType: ...

class AttributeType: ...

class Attribute:
    @classmethod
    def apply(cls, player: "Player", attribute_type: "AttributeType" | str, base_value: float) -> Awaitable[Any]: ...
    attribute_type: "AttributeType"
    value: float
    base_value: float
    def set_base_value(self, value: float) -> Awaitable[None]: ...

class GameMode: ...
class Sound: ...
class Particle: ...
class Difficulty: ...

class Vector:
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0): ...
    x: float
    y: float
    z: float

class BarColor: ...
class BarStyle: ...

class BossBar:
    @classmethod
    def create(cls, title: str, color: "BarColor" | None = None, style: "BarStyle" | None = None, players: list["Player"] | None = None) -> Awaitable["BossBar"]: ...
    def add_player(self, player: "Player") -> Awaitable[None]: ...
    def remove_player(self, player: "Player") -> Awaitable[None]: ...
    title: str
    def set_title(self, title: str) -> Awaitable[None]: ...
    progress: float
    def set_progress(self, value: float) -> Awaitable[None]: ...
    color: "BarColor"
    def set_color(self, color: "BarColor") -> Awaitable[None]: ...
    style: "BarStyle"
    def set_style(self, style: "BarStyle") -> Awaitable[None]: ...
    visible: bool
    def set_visible(self, value: bool) -> Awaitable[None]: ...

class Scoreboard:
    @classmethod
    def create(cls) -> Awaitable["Scoreboard"]: ...
    def register_objective(self, name: str, criteria: str, display_name: str = "") -> Awaitable["Objective"]: ...
    def get_team(self, name: str) -> Awaitable["Team"]: ...
    def register_team(self, name: str) -> Awaitable["Team"]: ...
    def get_objective(self, name: str) -> Awaitable["Objective"]: ...
    objectives: list["Objective"]
    teams: list["Team"]
    def clear_slot(self, slot: Any) -> Awaitable[None]: ...

class Team:
    @classmethod
    def create(cls, name: str, scoreboard: "Scoreboard" | None = None) -> Awaitable["Team"]: ...
    def add_entry(self, entry: str) -> Awaitable[None]: ...
    def remove_entry(self, entry: str) -> Awaitable[None]: ...
    def set_prefix(self, prefix: str) -> Awaitable[None]: ...
    def set_suffix(self, suffix: str) -> Awaitable[None]: ...
    color: Any
    def set_color(self, color: Any) -> Awaitable[None]: ...
    entries: set[str]

class Objective:
    @classmethod
    def create(cls, name: str, criteria: str, display_name: str = "", scoreboard: "Scoreboard" | None = None) -> Awaitable["Objective"]: ...
    def set_display_name(self, name: str) -> Awaitable[None]: ...
    def get_score(self, entry: str) -> Awaitable[Any]: ...
    name: str
    criteria: str
    display_slot: Any
    def set_display_slot(self, slot: Any) -> Awaitable[None]: ...

class Advancement:
    @classmethod
    def grant(cls, player: "Player", key: str) -> Awaitable["AdvancementProgress"]: ...
    @classmethod
    def revoke(cls, player: "Player", key: str) -> Awaitable["AdvancementProgress"]: ...
    key: Any

class AdvancementProgress:
    is_done: bool
    def award_criteria(self, name: str) -> Awaitable[bool]: ...
    def revoke_criteria(self, name: str) -> Awaitable[bool]: ...
    remaining_criteria: set[str]
    awarded_criteria: set[str]

class Potion:
    @classmethod
    def apply(cls, player: "Player", effect_type: "EffectType" | str | None = None, duration: int = 0, amplifier: int = 0, ambient: bool = False, particles: bool = True, icon: bool = True) -> Awaitable[Any]: ...
    type: Any
    level: int

class Server:
    def broadcast(self, message: str) -> Awaitable[None]: ...
    players: list["Player"]
    worlds: list["World"]
    def world(self, name: str) -> Awaitable["World"]: ...
    scoreboard_manager: Any
    def create_boss_bar(self, title: str, color: "BarColor", style: "BarStyle") -> Awaitable["BossBar"]: ...
    boss_bars: list["BossBar"]
    def get_advancement(self, key: str) -> Awaitable["Advancement"]: ...
    plugin_manager: Any
    scheduler: Any
    def wait(self, ticks: int = 1, after: Callable[[], Any] | None = None) -> Awaitable[None]: ...
    def frame(self) -> Any: ...
    def atomic(self) -> Any: ...
    def flush(self) -> Awaitable[None]: ...
    name: str
    version: str
    motd: str
    max_players: int
    tps: list[float]
    mspt: float
    last_tick_time: float
    queue_len: int

class Chat:
    def broadcast(self, message: str) -> Awaitable[None]: ...

class Reflect:
    def clazz(self, name: str) -> Awaitable[Any]: ...

server: Server
chat: Chat
reflect: Reflect


def event(func: Optional[Callable] = None, *, once_per_tick: bool = False): ...

def command(name: Optional[str] = None): ...

def raycast(
    world: World | str,
    start: Vector|tuple[float,float,float],
    direction: tuple[float,float],
    max_distance: float = 64.0,
    ray_size: float = 0.2,
    include_entities: bool = True,
    include_blocks: bool = True,
    ignore_passable: bool = True,
) -> Awaitable[RaycastResult | None]: ...
