name: PyJavaBridge
main: com.pyjavabridge.PyJavaBridgePlugin
version: '${version}'
api: '1.21'
api-version: '1.21'
author: Omena0
softdepend:
  - ProtocolLib
commands:
  bridge:
    description: Manage PyJavaBridge
    usage: /bridge reload [<script>] | /bridge debug
    permission: pyjavabridge.admin
  pjbperm:
    description: Reply to a client permission request (internal)
    usage: /pjbperm <requestId> <accept|deny> [remember]
    permission: false
permissions:
  pyjavabridge.admin:
    default: op
