from typing import Any, Callable
from enum import Enum
from bridge.wrappers import ItemBuilder


# ── NPC ──────────────────────────────────────────────────────────────
class NPC:
    def __init__(self, entity: Any, name: str | None = None) -> None: ...
    @classmethod
    async def spawn(cls, location: Any, entity_type: Any = "VILLAGER", name: str | None = None, **kwargs: Any) -> "NPC": ...
    @property
    def entity(self) -> Any: ...
    @property
    def uuid(self) -> str | None: ...
    @property
    def location(self) -> Any: ...
    def on_click(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_right_click(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_range_enter(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_range_exit(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def dialog(self, messages: list[str], loop: bool = False) -> None: ...
    async def move_to(self, location: Any, speed: float = 1.0) -> Any: ...
    async def follow_path(self, waypoints: list[Any], loop: bool = False, speed: float = 1.0, delay: float = 0.5) -> None: ...
    def stop_path(self) -> None: ...
    def link_dialog(self, dialog: "Dialog") -> None: ...
    def link_player(self, player: Any) -> None: ...
    def set_range(self, distance: float) -> None: ...
    async def remove(self) -> None: ...

# ── ImageDisplay ─────────────────────────────────────────────────────
class ImageDisplay:
    def __init__(self, location: Any, image: str | Any, pixel_size: float = ..., dual_sided: bool = False, dual_side_mode: str = "mirror") -> None: ...
    def teleport(self, location: Any) -> None: ...
    def remove(self) -> None: ...
    def update(self, image: str | Any) -> None: ...

# ── MeshDisplay ──────────────────────────────────────────────────────
class MeshDisplay:
    def __init__(self, location: Any, vertices: list[tuple[float, float, float]], faces: list[tuple[int, int, int]], face_colors: list[tuple[int, int, int, int]] | None = None, vertex_colors: list[tuple[int, int, int, int]] | None = None, texture: Any = None, uvs: list[tuple[float, float]] | None = None, face_uvs: list[tuple[int, int, int]] | None = None, pixel_size: float = ..., dual_sided: bool = False) -> None: ...
    def remove(self) -> None: ...
    def update(self, face_colors: list[tuple[int, int, int, int]] | None = None, vertex_colors: list[tuple[int, int, int, int]] | None = None) -> None: ...
    def update_geometry(self, vertices: list[tuple[float, float, float]], face_colors: list[tuple[int, int, int, int]] | None = None, vertex_colors: list[tuple[int, int, int, int]] | None = None) -> None: ...

# ── Quest ────────────────────────────────────────────────────────────
class Quest:
    name: str
    description: str
    time_limit: float | None
    def __init__(self, name: str, description: str = "", time_limit: float | None = None) -> None: ...
    def on_complete(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
    def progress_getter(self, func: Callable[..., float]) -> Callable[..., float]: ...
    def status(self, player: Any) -> str: ...
    def progress(self, player: Any) -> float: ...
    def start_time(self, player: Any) -> float | None: ...
    def end_time(self, player: Any) -> float | None: ...
    def accept(self, player: Any) -> None: ...
    def start(self, player: Any) -> None: ...
    def complete(self, player: Any) -> None: ...
    def fail(self, player: Any) -> None: ...
    def end(self, player: Any) -> None: ...
    def show_bar(self, player: Any, color: str = "GREEN", style: str = "SEGMENTED_10") -> None: ...
    def hide_bar(self, player: Any) -> None: ...

class QuestTree:
    depth: int
    def __init__(self, tree: list[list[Quest] | Quest]) -> None: ...
    def current_depth(self, player: Any) -> int: ...
    def available(self, player: Any) -> list[Quest]: ...
    def active(self, player: Any) -> list[Quest]: ...
    def is_complete(self, player: Any) -> bool: ...
    def all_quests(self) -> list[Quest]: ...

# ── Dialog ───────────────────────────────────────────────────────────
class DialogEntry:
    speaker: str
    text: str
    answers: list[tuple[str, "DialogEntry | Callable[..., Any]"]]
    delay: float | None
    def __init__(self, speaker: str, text: str, answers: list[tuple[str, "DialogEntry | Callable[..., Any]"]] | None = None, delay: float | None = None) -> None: ...

class Dialog:
    def __init__(self, root: DialogEntry) -> None: ...
    def start(self, player: Any) -> None: ...
    def stop(self, player: Any) -> None: ...
    def is_active(self, player: Any) -> bool: ...

# ── Bank ─────────────────────────────────────────────────────────────
class Bank:
    name: str
    currency: str
    def __init__(self, name: str = "default", currency: str = "coins") -> None: ...
    def on_transaction(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def balance(self, player: Any) -> int: ...
    def deposit(self, player: Any, amount: int) -> None: ...
    def withdraw(self, player: Any, amount: int) -> bool: ...
    def transfer(self, source: Any, target: Any, amount: int) -> bool: ...
    def set_balance(self, player: Any, amount: int) -> None: ...
    @classmethod
    def get(cls, name: str = "default") -> "Bank | None": ...

# ── Shop ─────────────────────────────────────────────────────────────
class Shop:
    name: str
    items: list[tuple[Any, int]]
    def __init__(self, name: str = "Shop", bank: Bank | None = None, rows: int = 6) -> None: ...
    def on_purchase(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def add_item(self, item: Any, price: int) -> None: ...
    def remove_item(self, index: int) -> None: ...
    def open(self, player: Any, page: int = 0) -> None: ...
    def close(self, player: Any) -> None: ...

# ── TradeWindow ──────────────────────────────────────────────────────
class TradeWindow:
    def __init__(self, bank: Bank | None = None, delay: float = 3.0) -> None: ...
    def on_trade(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def open(self, p1: Any, p2: Any) -> None: ...
    def close(self, player: Any) -> None: ...

# ── Ability ──────────────────────────────────────────────────────────
class Ability:
    name: str
    description: str
    cooldown: float
    use_cost: float | None
    cooldown_msg: str
    display_bossbar: bool
    def __init__(self, name: str, description: str = "", cooldown: float = 1.0, use_cost: float | None = None, cooldown_msg: str = "§cAbility on cooldown! {remaining:.1f}s", display_bossbar: bool = False) -> None: ...
    def on_use(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
    def can_use(self, func: Callable[..., bool]) -> Callable[..., bool]: ...
    def set_mana_store(self, mana_store: "ManaStore") -> None: ...
    def last_used(self, player: Any) -> float | None: ...
    def remaining_cooldown(self, player: Any) -> float: ...
    def use(self, player: Any) -> bool: ...

# ── ManaStore ────────────────────────────────────────────────────────
class ManaStore:
    default_mana: float
    default_max_mana: float
    default_regen_rate: float
    display_bossbar: bool
    def __init__(self, default_mana: float = 100.0, default_max_mana: float = 100.0, default_regen_rate: float = 1.0, display_bossbar: bool = False) -> None: ...
    def __getitem__(self, player: Any) -> float: ...
    def __setitem__(self, player: Any, value: float) -> None: ...
    def max_mana(self, player: Any) -> float: ...
    def set_max_mana(self, player: Any, value: float) -> None: ...
    def regen_rate(self, player: Any) -> float: ...
    def set_regen_rate(self, player: Any, value: float) -> None: ...
    def consume(self, player: Any, amount: float) -> bool: ...
    def restore(self, player: Any, amount: float) -> None: ...
    def start_regen(self) -> None: ...

# ── CombatSystem ─────────────────────────────────────────────────────
class CombatSystem:
    combat_timeout: float
    display_bossbar: bool
    def __init__(self, combat_timeout: float = 10.0, display_bossbar: bool = False) -> None: ...
    def on_combat_log(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def start(self) -> None: ...
    def in_combat(self, player: Any) -> bool: ...
    def in_combat_by_uuid(self, puuid: str) -> bool: ...
    def remaining(self, player: Any) -> float: ...

# ── LevelSystem ──────────────────────────────────────────────────────
class LevelSystem:
    multiplier: float
    exponent: float
    def __init__(self, multiplier: float = 100.0, exponent: float = 1.5, persist: bool = True, name: str = "levels") -> None: ...
    def __getitem__(self, player: Any) -> int: ...
    def on_level_up(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def xp_for_level(self, level: int) -> float: ...
    def level_from_xp(self, xp: float) -> int: ...
    def xp(self, player: Any) -> float: ...
    def level(self, player: Any) -> int: ...
    def add_xp(self, player: Any, amount: float) -> None: ...
    def set_xp(self, player: Any, value: float) -> None: ...
    def set_level(self, player: Any, level: int) -> None: ...
    def xp_to_next(self, player: Any) -> float: ...
    def progress(self, player: Any) -> float: ...

# ── Region ───────────────────────────────────────────────────────────
class Region:
    name: str
    x1: float
    y1: float
    z1: float
    x2: float
    y2: float
    z2: float
    def __init__(self, name: str, world: Any, x1: float, y1: float, z1: float, x2: float, y2: float, z2: float) -> None: ...
    @property
    def world(self) -> str: ...
    def on_enter(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_exit(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def contains(self, location: Any) -> bool: ...
    def is_inside(self, player: Any) -> bool: ...
    def remove(self) -> None: ...

# ── Party ────────────────────────────────────────────────────────────
class Party:
    name: str
    leader: Any
    members: list[Any]
    member_uuids: list[str]
    size: int
    def __init__(self, name: str, leader: Any, max_size: int = 4) -> None: ...
    def on_join(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_leave(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_disband(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def is_member(self, player: Any) -> bool: ...
    def is_leader(self, player: Any) -> bool: ...
    def join(self, player: Any) -> bool: ...
    def leave(self, player: Any) -> None: ...
    def kick(self, player: Any) -> None: ...
    def promote(self, player: Any) -> None: ...
    def disband(self) -> None: ...
    def broadcast(self, message: str) -> None: ...
    @classmethod
    def of(cls, player: Any) -> "Party | None": ...

# ── Guild ────────────────────────────────────────────────────────────
class Guild:
    name: str
    leader_uuid: str
    members: dict[str, str]
    size: int
    bank: Bank
    def __init__(self, name: str, leader: Any, max_size: int = 50, bank: Bank | None = None) -> None: ...
    def on_join(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_leave(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_disband(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def is_member(self, player: Any) -> bool: ...
    def rank(self, player: Any) -> str | None: ...
    def join(self, player: Any) -> bool: ...
    def leave(self, player: Any) -> None: ...
    def kick(self, player: Any) -> None: ...
    def promote(self, player: Any, rank: str = "officer") -> None: ...
    def demote(self, player: Any) -> None: ...
    def transfer_leadership(self, new_leader: Any) -> None: ...
    def disband(self) -> None: ...
    def broadcast(self, message: str) -> None: ...
    @classmethod
    def load(cls, name: str) -> "Guild | None": ...
    @classmethod
    def of(cls, player: Any) -> "Guild | None": ...
    @classmethod
    def get(cls, name: str) -> "Guild | None": ...

# ── CustomItem ───────────────────────────────────────────────────────
class CustomItem(ItemBuilder):
    item_id: str
    def __init__(self, item_id: str, material: str = "DIAMOND") -> None: ...
    def give(self, player: Any, amount: int = 1) -> None: ...
    @classmethod
    def get(cls, item_id: str) -> "CustomItem | None": ...
    @classmethod
    def all(cls) -> dict[str, "CustomItem"]: ...

# ── Leaderboard ──────────────────────────────────────────────────────
class Leaderboard:
    title: str
    update_interval: int
    max_entries: int
    def __init__(self, location: Any, title: str = "Leaderboard", get_metric: Callable[..., Any] | None = None, update_interval: int = 100, max_entries: int = 10) -> None: ...
    def metric(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

# ── VisualEffect ─────────────────────────────────────────────────────
class VisualEffect:
    name: str
    def __init__(self, name: str = "effect") -> None: ...
    def step(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
    def add_step(self, func: Callable[..., Any]) -> None: ...
    async def trigger(self, location: Any) -> None: ...

# ── PlayerDataStore ──────────────────────────────────────────────────
class _PlayerView:
    def __getitem__(self, field: str) -> Any: ...
    def __setitem__(self, field: str, value: Any) -> None: ...
    def __delitem__(self, field: str) -> None: ...
    def __contains__(self, field: str) -> bool: ...
    def get(self, field: str, default: Any = None) -> Any: ...

class PlayerDataStore:
    name: str
    def __init__(self, name: str = "default") -> None: ...
    def __getitem__(self, player: Any) -> _PlayerView: ...
    def __setitem__(self, player: Any, value: dict[str, Any]) -> None: ...
    def get(self, player: Any, field: str, default: Any = None) -> Any: ...
    def set(self, player: Any, field: str, value: Any) -> None: ...
    def delete(self, player: Any, field: str | None = None) -> None: ...
    def all_data(self, player: Any) -> dict[str, Any]: ...

# ── Dungeon ──────────────────────────────────────────────────────────
class RoomType(Enum):
    HALLWAY = "hallway"
    COMBAT = "combat"
    PUZZLE = "puzzle"
    TREASURE = "treasure"
    TRAP = "trap"
    BOSS = "boss"

class DungeonRoom:
    CONSTRAINTS: dict[RoomType, dict[str, Any]]
    room_type: RoomType
    mobs: list[Any]
    cleared: bool
    grid_x: int
    grid_z: int
    def __init__(self, room_type: RoomType = RoomType.HALLWAY, mobs: list[Any] | None = None) -> None: ...
    def on_enter(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_clear(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def mark_cleared(self) -> None: ...

class DungeonInstance:
    dungeon: "Dungeon"
    players: list[Any]
    instance_id: int
    rooms: list[DungeonRoom]
    progress: float
    is_complete: bool
    def __init__(self, dungeon: "Dungeon", players: list[Any], instance_id: int) -> None: ...
    def on_enter(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_exit(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_complete(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def generate(self, room_count: int = 12, grid_size: int = 8) -> None: ...
    async def complete(self) -> None: ...
    def destroy(self) -> None: ...

class Dungeon:
    name: str
    description: str
    difficulty: int
    recommended_level: int
    room_count: int
    grid_size: int
    instances: list[DungeonInstance]
    def __init__(self, name: str, description: str = "", difficulty: int = 1, recommended_level: int = 1, room_count: int = 12, grid_size: int = 8) -> None: ...
    def on_enter(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_exit(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_complete(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_room_enter(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on_room_clear(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def reward(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def create_instance(self, players: list[Any], room_count: int | None = None, grid_size: int | None = None) -> DungeonInstance: ...



