from __future__ import annotations

from typing import Any, AsyncIterable, Callable, Dict, Iterable, List, Optional
from bridge.types import BridgeCall


class ClientModSession:
    player: Any
    def __init__(self, player: Any) -> None: ...
    def is_available(self) -> BridgeCall: ...
    def command(self, capability: str, args: Dict[str, Any] | None = None,
        handle: Optional[str] | None = None, timeout_ms: int = 1000) -> BridgeCall: ...
    def data(self, channel: str, payload: Dict[str, Any] | None = None,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def register_script(self, name: str, source: str, auto_start: bool = True,
        metadata: Dict[str, Any] | None = None, timeout_ms: int = 2000) -> BridgeCall: ...
    def set_permissions(self, capabilities: List[str], reason: Optional[str] = None,
        remember_prompt: bool = True, timeout_ms: int = 60000) -> BridgeCall: ...
    def get_permissions(self) -> BridgeCall: ...
    def raycast(self, max_distance: float = 64.0, include_fluids: bool = False,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def entities_list(self, query: Dict[str, Any] | None = None,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def entities_query(self, query: Dict[str, Any] | None = None,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def particles_spawn(self, particle: str = "minecraft:smoke", x: float | None = None,
        y: float | None = None, z: float | None = None, vx: float = 0.0, vy: float = 0.0,
        vz: float = 0.0, count: int = 1, spread: float = 0.0, timeout_ms: int = 1000) -> BridgeCall: ...
    def metrics_get(self, timeout_ms: int = 1000) -> BridgeCall: ...
    def stream_audio_file(self, path: str, stream_id: str | None = None,
        sample_rate: int = 48000, channels: int = 2, chunk_size: int = 4096,
        stop_when_done: bool = True) -> BridgeCall: ...
    def stream_audio_generator(self,
        gen: Callable[[], AsyncIterable[bytes] | Iterable[bytes]] | AsyncIterable[bytes] | Iterable[bytes],
        stream_id: str | None = None, sample_rate: int = 48000, channels: int = 2,
        chunk_size: int = 4096, stop_when_done: bool = True) -> BridgeCall: ...
    def mic_set_mute(self, muted: bool = True, timeout_ms: int = 1000) -> BridgeCall: ...
    def mic_get_state(self, timeout_ms: int = 1000) -> BridgeCall: ...
    def mic_level_subscribe(self, stream_id: str, interval_ms: int = 250,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def mic_level_unsubscribe(self, stream_id: str,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def mic_vad_set(self, enabled: bool, threshold: float = 0.02,
        min_speech_ms: int = 200, timeout_ms: int = 1000) -> BridgeCall: ...
    def audio_stream_set_volume(self, stream_id: str, volume: float = 1.0,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def audio_stream_pause(self, stream_id: str,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def audio_stream_resume(self, stream_id: str,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def voice_subscribe(self, stream_id: str, source_player: str | None = None,
        mix: bool = False, timeout_ms: int = 1000) -> BridgeCall: ...
    def voice_unsubscribe(self, stream_id: str,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def ui_prompt_confirm(self, title: str | None = None, message: str | None = None,
        remember_option: bool = False, timeout_ms: int = 60000) -> BridgeCall: ...
    def client_pref_set(self, key: str, value: Any,
        timeout_ms: int = 1000) -> BridgeCall: ...
    def client_pref_get(self, key: str,
        timeout_ms: int = 1000) -> BridgeCall: ...


class ClientMod:
    def session(self, player: Any) -> ClientModSession: ...
    def for_player(self, player: Any) -> ClientModSession: ...
    def player(self, player: Any) -> ClientModSession: ...
    def register_request_data(self, key: str, value: Any) -> BridgeCall: ...
    def unregister_request_data(self, key: str) -> BridgeCall: ...
    def on_client_data(self, handler: Callable[[Any], Any]) -> Callable[[Any], Any]: ...
    def on_permission_change(self, handler: Callable[[Any], Any]) -> Callable[[Any], Any]: ...


client_mod: ClientMod
