"""LootTable extension — custom loot tables with weights, conditions, and rolls."""
from __future__ import annotations

import random
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional, Tuple

if TYPE_CHECKING:
    from bridge import Item
    from bridge import Inventory

class LootEntry:
    """A single entry in a loot pool.

    Args:
        item: Material name or dict with ``{"material": ..., "amount": ..., "name": ...}``.
        weight: Relative probability weight. Default 1.
        min_amount: Minimum stack size. Default 1.
        max_amount: Maximum stack size. Default 1.
        condition: Optional callable ``(context) -> bool`` that must return True for this entry to drop.
    """
    __slots__ = ("item", "weight", "min_amount", "max_amount", "condition")

    def __init__(self, item: Any, weight: int = 1, min_amount: int = 1,
            max_amount: int = 1, condition: Optional[Callable[..., bool]] = None) -> None:
        """Initialise a new LootEntry."""
        self.item = item
        self.weight = max(1, weight)
        self.min_amount = min_amount
        self.max_amount = max_amount
        self.condition = condition

    def _matches(self, context: Any) -> bool:
        """Handle matches."""
        if self.condition is None:
            return True

        try:
            return bool(self.condition(context))
        except Exception:
            return False

    def _roll_amount(self) -> int:
        """Return the roll amount."""
        return random.randint(self.min_amount, self.max_amount)

    def _resolve_item(self) -> Optional["Item"]:
        """Return a dropped Item object or None if the roll is empty."""
        rolled_amount = self._roll_amount()

        if isinstance(self.item, dict):
            result = dict(self.item)
            result.setdefault("amount", rolled_amount)
            amount = int(result.get("amount", 1))
            if amount <= 0:
                return None
            return _item_from_dict(result)

        # Support passing bridge Item objects directly.
        # Item proxies store local creation data in `.fields`.
        item_fields = getattr(self.item, "fields", None)
        if isinstance(item_fields, dict):
            amount = int(item_fields.get("amount", rolled_amount))
            return _clone_item_with_amount(self.item, amount)

        if rolled_amount <= 0:
            return None

        return _item_from_dict({"material": str(self.item), "amount": rolled_amount})


def _item_from_dict(item_data: dict) -> "Item":
    """Build an Item using public constructor args/properties only."""
    from bridge import Item

    material = item_data.get("material") or item_data.get("type")
    amount = int(item_data.get("amount", 1))
    item = Item(material=material, amount=amount)

    if "name" in item_data and item_data["name"] is not None:
        item.name = str(item_data["name"])
    if "lore" in item_data and item_data["lore"] is not None:
        item.lore = list(item_data["lore"])
    if "customModelData" in item_data and item_data["customModelData"] is not None:
        item.custom_model_data = int(item_data["customModelData"])
    if "attributes" in item_data and item_data["attributes"] is not None:
        item.attributes = list(item_data["attributes"])
    if "nbt" in item_data and item_data["nbt"] is not None:
        item.nbt = dict(item_data["nbt"])

    # Preserve additional metadata generated by builders/custom items.
    handled_keys = {
        "material",
        "type",
        "amount",
        "name",
        "lore",
        "customModelData",
        "attributes",
        "nbt",
    }
    for key, value in item_data.items():
        if key in handled_keys or value is None:
            continue
        item.fields[key] = value

    return item


def _clone_item_with_amount(item: "Item", amount: int) -> Optional["Item"]:
    """Clone an item proxy and override amount; return None for empty stacks."""
    if amount <= 0:
        return None

    fields = dict(getattr(item, "fields", {}) or {})
    fields["amount"] = int(amount)
    material = fields.get("material") or fields.get("type")
    if material is not None:
        fields["material"] = str(material)

    return _item_from_dict(fields)


def _spread_into_inventory(inventory: "Inventory", items: List["Item"]) -> List["Item"]:
    """Place items into random slots (vanilla-like spread) and return inserted items."""
    if not items:
        return []

    size = int(inventory.size)
    if size <= 0:
        return []

    raw_contents = inventory.contents
    if raw_contents is None:
        contents: List[Any] = []
    elif isinstance(raw_contents, list):
        contents = list(raw_contents)
    else:
        # Some bridge backends may return a single Item instead of a list.
        try:
            contents = list(raw_contents)
        except TypeError:
            contents = [raw_contents]

    while len(contents) < size:
        contents.append(None)

    slots = list(range(size))
    random.shuffle(slots)

    inserted: List[Item] = []
    item_iter = iter(items)

    # Fill random empty slots first.
    for slot in slots:
        if contents[slot] is not None:
            continue
        try:
            item = next(item_iter)
        except StopIteration:
            return inserted

        if inventory._handle is None:
            inventory.set_item(slot, item)
        else:
            inventory._call_sync("setItem", slot, item)
        inserted.append(item)

    # If inventory is full, try vanilla add behavior (stacking/appending where possible).
    for item in item_iter:
        if inventory._handle is None:
            inventory.add_item(item)
            inserted.append(item)
            continue

        try:
            inventory._call_sync("addItem", item)
            inserted.append(item)
        except Exception:
            break

    return inserted

class LootPool:
    """A pool of loot entries with configurable rolls.

    Args:
        name: Pool identifier.
        rolls: Number of items to pick per generation. Default 1.
        bonus_rolls: Extra rolls based on luck. Default 0.
    """

    def __init__(self, name: str = "pool", rolls: int = 1, bonus_rolls: int = 0) -> None:
        """Initialise a new LootPool."""
        self.name = name
        self.rolls = rolls
        self.bonus_rolls = bonus_rolls
        self._entries: List[LootEntry] = []

    def add(
            self, item: Any, weight: int = 1, min_amount: int = 1,
            max_amount: int = 1,
            condition: Optional[Callable[..., bool]] = None,
    ) -> LootEntry:
        """Add an entry to this pool.

        Args:
            item: Material name or item dict.
            weight: Relative probability weight.
            min_amount: Minimum stack size.
            max_amount: Maximum stack size.
            condition: Optional condition function.
        """
        entry = LootEntry(item, weight, min_amount, max_amount, condition)
        self._entries.append(entry)
        return entry

    def entry(self, item: Any, weight: int = 1, min_amount: int = 1,
            max_amount: int = 1,
            condition: Optional[Callable[..., bool]] = None) -> Any:
        """Decorator-style entry registration. Returns the condition function."""
        def decorator(func: Callable[..., bool]) -> Callable[..., bool]:
            """Register as a decorator."""
            self.add(item, weight, min_amount, max_amount, condition=func)
            return func

        return decorator

    def generate(self, context: Any = None, luck: float = 0.0) -> List["Item"]:
        """Generate loot from this pool.

        Args:
            context: Arbitrary context passed to condition functions.
            luck: Luck factor that scales bonus_rolls.

        Returns:
            List of :class:`bridge.Item` objects representing dropped items.
        """
        eligible = [e for e in self._entries if e._matches(context)]
        if not eligible:
            return []

        total_rolls = self.rolls + int(self.bonus_rolls * luck)
        total_rolls = max(0, total_rolls)

        weights = [e.weight for e in eligible]
        results: List[Item] = []

        for _ in range(total_rolls):
            chosen = random.choices(eligible, weights=weights, k=1)[0]
            item_obj = chosen._resolve_item()
            if item_obj is None:
                continue
            results.append(item_obj)

        return results

    def generate_into(self, inventory: "Inventory", context: Any = None,
            luck: float = 0.0) -> List["Item"]:
        """Generate loot and insert it into an inventory with random slot spread.

        Args:
            inventory: Target inventory.
            context: Arbitrary context passed to condition functions.
            luck: Luck factor that scales bonus_rolls.

        Returns:
            List of inserted :class:`bridge.Item` objects.
        """
        items = self.generate(context=context, luck=luck)
        return _spread_into_inventory(inventory, items)

class LootTable:
    """Custom loot table with multiple pools.

    Example::
        loot = LootTable("dungeon_chest")

        common = loot.add_pool("common", rolls=3)
        common.add("IRON_INGOT", weight=10, min_amount=1, max_amount=5)
        common.add("GOLD_INGOT", weight=5, min_amount=1, max_amount=3)
        common.add("DIAMOND", weight=1)

        rare = loot.add_pool("rare", rolls=1, bonus_rolls=1)
        rare.add("ENCHANTED_GOLDEN_APPLE", weight=1, condition=lambda ctx: ctx.get("difficulty") == "hard")
        rare.add("GOLDEN_APPLE", weight=5)

        # Generate loot
        items = loot.generate(context={"difficulty": "hard"}, luck=1.0)
        # -> [Item(...), Item(...), ...]
        # Give to player
        for item in items:
            await player.inventory.add_item(item)
    """

    def __init__(self, name: str = "loot_table") -> None:
        """Initialise a new LootTable."""
        self.name = name
        self._pools: Dict[str, LootPool] = {}

    def add_pool(self, name: str = "pool", rolls: int = 1,
            bonus_rolls: int = 0) -> LootPool:
        """Add a loot pool to this table."""
        pool = LootPool(name, rolls, bonus_rolls)
        self._pools[name] = pool
        return pool

    def get_pool(self, name: str) -> Optional[LootPool]:
        """Return the pool."""
        return self._pools.get(name)

    def remove_pool(self, name: str) -> None:
        """Remove a pool."""
        self._pools.pop(name, None)

    @property
    def pools(self) -> List[LootPool]:
        """The pools value."""
        return list(self._pools.values())

    def generate(self, context: Any = None, luck: float = 0.0) -> List["Item"]:
        """Generate loot from all pools.

        Args:
            context: Arbitrary context passed to all pool condition functions.
            luck: Luck factor applied to bonus rolls in all pools.

        Returns:
            Combined list of :class:`bridge.Item` objects from all pools.
        """
        results: List[Item] = []
        for pool in self._pools.values():
            results.extend(pool.generate(context, luck))

        return results

    def generate_into(self, inventory: "Inventory", context: Any = None,
            luck: float = 0.0) -> List["Item"]:
        """Generate loot from all pools and insert into inventory with random spread.

        Args:
            inventory: Target inventory.
            context: Arbitrary context passed to all pool condition functions.
            luck: Luck factor applied to bonus rolls in all pools.

        Returns:
            List of inserted :class:`bridge.Item` objects.
        """
        items = self.generate(context=context, luck=luck)
        return _spread_into_inventory(inventory, items)

    def generate_stacked(self, context: Any = None,
            luck: float = 0.0) -> List["Item"]:
        """Generate loot and combine items of the same material into stacks.

        Returns:
            List of :class:`bridge.Item` objects with amounts combined.
        """
        raw = self.generate(context, luck)
        stacked: Dict[str, Item] = {}
        for item in raw:
            key = str(item.fields.get("material", ""))
            if key in stacked:
                existing_amt = int(stacked[key].fields.get("amount", 1))
                add_amt = int(item.fields.get("amount", 1))
                stacked[key].fields["amount"] = existing_amt + add_amt
            else:
                stacked[key] = item

        return list(stacked.values())
